/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the `php5' library (-lphp5). */
#define HAVE_LIBPHP5 1

/* Name of package */
#define PACKAGE "opcodes_dumper"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://projects.laruence.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "opcodes_dumper"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "opcodes_dumper 1.0.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "opcodes_dumper"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.0"

/* Version number of package */
#define VERSION "1.0.0"
